services:
  postgres-api:
    image: postgres:14.3
    container_name: portfolio_database
    ports:
      - '5555:5432'
    environment:
      POSTGRES_USER: 'portfolio_manager'
      POSTGRES_PASSWORD: 'portfolio_manager'
      ALL_POSTGRES_DBS: 'portfolio,portfolio_test'
      MIGRATION_SCRIPT: '/docker-entrypoint-initdb.d/migrations.sql'
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./.docker-data/.pg-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: portfolio_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/mnesia
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq
