name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - '**'

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    needs: unit-tests
    uses: ./.github/workflows/integration-tests.yml
