name: Run Pytest

on:
  push:
    branches:
      - main
      - master
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      working-directory: api
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r src/requirements.txt
        pip install -r src/api/requirements.txt 
        pip install -r src/portfolio_management/requirements.txt 
        pip install -r src/shared/requirements.txt 
        pip install -r test/requirements.txt

    - name: Run Pytest with Coverage
      working-directory: api
      env:
        PYTHONPATH: ./src:./api:./portfolio_management
      run: |
        source .venv/bin/activate
        pytest test/ --cov=src --cov-report=xml
